# Generated by Django 6.0 on 2025-12-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_notes"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="The corresponding Price ID from Stripe, for synchronization.",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="The price amount.", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="The three-letter ISO currency code.",
                        max_length=3,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("one_time", "One-Time"), ("recurring", "Recurring")],
                        default="one_time",
                        help_text="Whether the price is for a one-time purchase or a subscription.",
                        max_length=10,
                    ),
                ),
                (
                    "recurring_interval",
                    models.CharField(
                        blank=True,
                        choices=[("month", "Month"), ("year", "Year")],
                        help_text="The frequency at which a subscription is billed. Required if type is 'recurring'.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if this price is currently active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The internal name of the product.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A customer-facing description of the product.",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        help_text="The corresponding Product ID from Stripe, for synchronization.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the product is currently available for purchase.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_charge_id",
            new_name="stripe_payment_intent_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The amount charged. Should match the linked price.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="price",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.price",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="payments.product",
            ),
        ),
    ]
