# Generated by Django 6.0 on 2025-12-22 02:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=5)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "backup_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "secondary_backup_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("backup_phone", models.CharField(blank=True, max_length=20)),
                (
                    "facebook_handle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instagram_handle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "snapchat_handle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("x_handle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if the user has verified their primary email address.",
                    ),
                ),
                (
                    "verification_email_last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the last verification email was sent.",
                        null=True,
                    ),
                ),
                (
                    "password_reset_last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the last password reset email was sent.",
                        null=True,
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp of when the account was anonymized.",
                        null=True,
                    ),
                ),
                (
                    "hash_first_name",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_last_name",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_email",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                (
                    "hash_country_code",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_phone",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_backup_email",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_secondary_backup_email",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_backup_phone",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_facebook_handle",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_instagram_handle",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_snapchat_handle",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hash_x_handle",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "agreed_to_terms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="data_management.termsandconditions",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
