# Generated by Django 5.2.9 on 2025-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emergencycontact",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="physical_address",
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="last_name",
            field=models.CharField(default="default_name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="backup_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="snapchat_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="x_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
