# Generated by Django 6.0 on 2025-12-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_last_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the last password reset email was sent.",
                null=True,
            ),
        ),
    ]
