# Generated by Django 6.0 on 2025-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_anonymized_at_user_hash_backup_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False,
                help_text="True if the user has verified their primary email address.",
            ),
        ),
    ]
