# Generated by Django 6.0 on 2025-12-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_email_last_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the last verification email was sent.",
                null=True,
            ),
        ),
    ]
