# Generated by Django 6.0 on 2025-12-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_notification_start_date"),
        ("payments", "0003_tier_remove_price_product_price_tier_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                help_text="The pricing tier for this event.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="payments.tier",
            ),
        ),
    ]
