# Generated by Django 6.0 on 2025-12-22 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_send_time", models.DateTimeField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("primary_email", "Primary Email"),
                            ("primary_sms", "Primary SMS"),
                            ("backup_email", "Backup Email"),
                            ("backup_sms", "Backup SMS"),
                            ("admin_call", "Admin Call Task"),
                            ("social_media", "Social Media Outreach Task"),
                            ("emergency_contact", "Emergency Contact Outreach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "recipient_contact_info",
                    models.CharField(
                        blank=True,
                        help_text="The contact info used for sending. Populated after the notification is sent.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_send_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_send_time"],
                        name="events_noti_status_d87fcf_idx",
                    )
                ],
            },
        ),
    ]
