# Generated by Django 6.0 on 2026-01-01 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="failure_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for failure, captured from provider or sending exception.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_sid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The unique identifier for the message from the provider (e.g., Twilio SID).",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["message_sid"], name="events_noti_message_021c14_idx"
            ),
        ),
    ]
