# Generated by Django 6.0 on 2026-01-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0007_notification_failure_reason_notification_message_sid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("primary_email", "Primary Email"),
                    ("primary_sms", "Primary SMS"),
                    ("backup_email", "Backup Email"),
                    ("backup_sms", "Backup SMS"),
                    ("social_media", "Social Media Outreach Task"),
                    ("emergency_contact_email", "Emergency Contact Email"),
                ],
                max_length=30,
            ),
        ),
    ]
