# Generated by Django 6.0 on 2026-01-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_notification_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message_sid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The unique identifier for the message from the provider (e.g., Twilio SID).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
