# Generated by Django 6.0 on 2026-01-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_notification_message_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("admin_task_created", "Admin Task Created"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
