# Generated by Django 6.0 on 2025-12-22 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="The email address to block.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the email was added to the blocklist.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Email",
                "verbose_name_plural": "Blocked Emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.TextField()),
                (
                    "pages",
                    models.JSONField(
                        default=list,
                        help_text='A list of page identifiers where this FAQ should appear (e.g., ["home", "substitutes"])',
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number, e.g., '1.0'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full HTML content of the terms and conditions."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this version was published.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Terms and Conditions",
                "ordering": ["-published_at"],
            },
        ),
    ]
